language: julia
dist: trusty
sudo: false
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
      - libnlopt0
after_success:
  - julia -e 'cd(Pkg.dir("TimeModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
